pull_request_rules:
  - name: Request reviews and label Stewards' PRs
    conditions:
      - or:
          - author=scala-steward
          - author=trace4cats-steward[bot]
    actions:
      request_reviews:
        users: [ janstenpickle, catostrophe ]
      label:
        add: [ dependency-update ]

  - name: Merge Stewards' PRs
    conditions:
      - or:
          - author=scala-steward
          - author=trace4cats-steward[bot]
      - or:
          - and:
              - "#files=1"
              - or:
                  - files=project/build.properties
                  - files=project/plugins.sbt
          - body~=labels:.*semver-patch
          - "#approved-reviews-by>=1"
      - and:
          - check-success~=Test \(ubuntu-latest, 2\.12\.\d+, adopt@1\.8\)
          - check-success~=Test \(ubuntu-latest, 2\.12\.\d+, adopt@1\.11\)
          - check-success~=Test \(ubuntu-latest, 2\.13\.\d+, adopt@1\.8\)
          - check-success~=Test \(ubuntu-latest, 2\.13\.\d+, adopt@1\.11\)
          - check-success~=Test \(ubuntu-latest, 3\.\d+\.\d+, adopt@1\.8\)
          - check-success~=Test \(ubuntu-latest, 3\.\d+\.\d+, adopt@1\.11\)
    actions:
      merge:
        method: rebase

  - name: Merge PRs via Mergify to skip the release step on CI
    conditions:
      - or:
          - author=janstenpickle
          - author=catostrophe
      - and:
          - label=skip-release
          - label=ready-to-merge
      - and:
          - check-success~=Test \(ubuntu-latest, 2\.12\.\d+, adopt@1\.8\)
          - check-success~=Test \(ubuntu-latest, 2\.12\.\d+, adopt@1\.11\)
          - check-success~=Test \(ubuntu-latest, 2\.13\.\d+, adopt@1\.8\)
          - check-success~=Test \(ubuntu-latest, 2\.13\.\d+, adopt@1\.11\)
          - check-success~=Test \(ubuntu-latest, 3\.\d+\.\d+, adopt@1\.8\)
          - check-success~=Test \(ubuntu-latest, 3\.\d+\.\d+, adopt@1\.11\)
    actions:
      merge:
        method: rebase

  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
