
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  queued_retry:

exporters:
  logging:
    logLevel: debug
  jaeger:
    endpoint: jaeger:14250
    insecure: true

service:

  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [logging, jaeger]

  extensions: [health_check, pprof, zpages]