addSbtPlugin("org.scalameta"             % "sbt-scalafmt"         % "2.5.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.4.2")
addSbtPlugin("com.github.sbt"            % "sbt-github-actions"   % "0.17.0")
addSbtPlugin("io.shiftleft"              % "sbt-ci-release-early" % "2.0.45")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"           % "4.1.1")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"        % "0.11.0")
